# Copyright 2017-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=6

CRATES="
adler32-1.0.2
aho-corasick-0.6.4
ansi_term-0.11.0
antidote-1.0.0
app_dirs-1.2.1
arrayref-0.3.4
atty-0.2.10
backtrace-0.3.8
backtrace-sys-0.1.23
base64-0.6.0
bitflags-0.9.1
bitflags-1.0.3
block-buffer-0.3.3
build_const-0.2.1
byte-tools-0.2.0
byteorder-1.2.3
bzip2-0.3.3
bzip2-sys-0.1.6
cc-1.0.17
cfg-if-0.1.3
clap-2.31.2
core-foundation-0.2.3
core-foundation-sys-0.2.3
crc-1.8.1
digest-0.7.2
error-chain-0.11.0
fake-simd-0.1.2
flate2-1.0.1
foreign-types-0.3.2
foreign-types-shared-0.1.1
fs2-0.4.3
fuchsia-zircon-0.3.3
fuchsia-zircon-sys-0.3.3
generic-array-0.9.0
httparse-1.2.4
hyper-0.10.13
hyper-native-tls-0.2.4
idna-0.1.4
language-tags-0.2.2
lazy_static-0.2.11
lazy_static-1.0.1
libc-0.2.42
log-0.3.9
log-0.4.2
matches-0.1.6
md-5-0.7.0
memchr-2.0.1
mime-0.2.6
miniz-sys-0.1.10
miniz_oxide-0.1.2
miniz_oxide_c_api-0.1.2
mkstemp-rs-0.0.2
msdos_time-0.1.6
native-tls-0.1.5
num_cpus-1.8.0
ole32-sys-0.2.0
openssl-0.9.24
openssl-sys-0.9.33
percent-encoding-1.0.1
pkg-config-0.3.11
podio-0.1.6
proc-macro2-0.4.6
quote-0.6.3
rand-0.4.2
redox_syscall-0.1.40
redox_termios-0.1.1
regex-0.2.11
regex-syntax-0.5.6
remove_dir_all-0.5.1
rustc-demangle-0.1.8
safemem-0.2.0
schannel-0.1.12
security-framework-0.1.16
security-framework-sys-0.1.16
serde-1.0.66
serde_derive-1.0.66
sha2-0.7.1
shell32-sys-0.1.2
strsim-0.7.0
syn-0.14.2
tectonic-0.1.8
tectonic_xdv-0.1.8
tempdir-0.3.7
termcolor-0.3.6
termion-1.5.1
textwrap-0.9.0
thread_local-0.3.5
time-0.1.40
toml-0.4.6
traitobject-0.1.0
typeable-0.1.2
typenum-1.10.0
ucd-util-0.1.1
unicase-1.4.2
unicode-bidi-0.3.4
unicode-normalization-0.1.7
unicode-width-0.1.5
unicode-xid-0.1.0
unreachable-1.0.0
url-1.7.0
utf8-ranges-1.0.0
vcpkg-0.2.4
vec_map-0.8.1
version_check-0.1.3
void-1.0.2
winapi-0.2.8
winapi-0.3.5
winapi-build-0.1.1
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
wincolor-0.1.6
xdg-2.1.0
zip-0.2.8
"

inherit cargo

DESCRIPTION="A modernized, complete, embeddable TeX/LaTeX engine"
HOMEPAGE="https://tectonic-typesetting.github.io/"
SRC_URI="https://github.com/tectonic-typesetting/${PN}/archive/v${PV}.tar.gz -> ${P}.tar.gz
	$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

DEPEND=""
RDEPEND=""
