# Copyright 2017-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=6

CRATES="
advapi32-sys-0.2.0
aho-corasick-0.6.3
ansi_term-0.9.0
antidote-1.0.0
app_dirs-1.1.1
atty-0.2.3
backtrace-0.3.4
backtrace-sys-0.1.16
base64-0.6.0
bitflags-0.7.0
bitflags-0.9.1
byte-tools-0.1.3
byteorder-1.1.0
bzip2-0.3.2
bzip2-sys-0.1.6
cc-1.0.3
cfg-if-0.1.2
clap-2.27.1
coco-0.1.1
core-foundation-0.2.3
core-foundation-sys-0.2.3
crypt32-sys-0.2.0
dbghelp-sys-0.2.0
digest-0.5.2
digest-buffer-0.3.1
either-1.4.0
error-chain-0.11.0
fake-simd-0.1.2
flate2-0.2.20
foreign-types-0.2.0
fs2-0.4.2
fuchsia-zircon-0.2.1
fuchsia-zircon-sys-0.2.0
gcc-0.3.54
generic-array-0.7.3
httparse-1.2.3
hyper-0.10.13
hyper-native-tls-0.2.4
idna-0.1.4
kernel32-sys-0.2.2
language-tags-0.2.2
lazy_static-0.2.10
libc-0.2.33
log-0.3.8
matches-0.1.6
md-5-0.4.4
memchr-1.0.2
mime-0.2.6
miniz-sys-0.1.10
mkstemp-rs-0.0.2
msdos_time-0.1.5
native-tls-0.1.4
nodrop-0.1.12
num_cpus-1.7.0
ole32-sys-0.2.0
openssl-0.9.20
openssl-sys-0.9.20
percent-encoding-1.0.1
pkg-config-0.3.9
podio-0.1.5
quote-0.3.15
rand-0.3.18
rayon-0.8.2
rayon-core-1.3.0
redox_syscall-0.1.31
redox_termios-0.1.1
regex-0.2.2
regex-syntax-0.4.1
rustc-demangle-0.1.5
safemem-0.2.0
schannel-0.1.8
scopeguard-0.3.3
secur32-sys-0.2.0
security-framework-0.1.16
security-framework-sys-0.1.16
serde-0.9.15
serde_codegen_internals-0.14.2
serde_derive-0.9.15
sha2-0.5.3
shell32-sys-0.1.1
strsim-0.6.0
syn-0.11.11
synom-0.11.3
tectonic-0.1.7
tempdir-0.3.5
termcolor-0.3.3
termion-1.5.1
textwrap-0.9.0
thread_local-0.3.4
time-0.1.38
toml-0.3.2
traitobject-0.1.0
typeable-0.1.2
typenum-1.9.0
unicase-1.4.2
unicode-bidi-0.3.4
unicode-normalization-0.1.5
unicode-width-0.1.4
unicode-xid-0.0.4
unreachable-1.0.0
url-1.6.0
utf8-ranges-1.0.0
vcpkg-0.2.2
vec_map-0.8.0
version_check-0.1.3
void-1.0.2
winapi-0.2.8
winapi-build-0.1.1
wincolor-0.1.4
xdg-2.1.0
zip-0.2.6
"

inherit cargo

DESCRIPTION="A modernized, complete, embeddable TeX/LaTeX engine"
HOMEPAGE="https://tectonic-typesetting.github.io/"
SRC_URI="https://github.com/tectonic-typesetting/${PN}/archive/v${PV}.tar.gz -> ${P}.tar.gz
	$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""
