# Copyright 2017-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=6

CRATES="
aho-corasick-0.6.4
ansi_term-0.10.2
atty-0.2.6
backtrace-0.3.5
backtrace-sys-0.1.16
bitflags-1.0.1
cc-1.0.4
cfg-if-0.1.2
chrono-0.4.0
clap-2.30.0
dtoa-0.4.2
env_logger-0.4.3
error-chain-0.11.0
glob-0.2.11
idna-0.1.4
itoa-0.3.4
kernel32-sys-0.2.2
lazy_static-0.2.11
lazy_static-1.0.0
libc-0.2.36
log-0.3.9
log-0.4.1
matches-0.1.6
memchr-2.0.1
num-0.1.42
num-integer-0.1.36
num-iter-0.1.35
num-traits-0.1.43
num-traits-0.2.0
percent-encoding-1.0.1
quote-0.3.15
redox_syscall-0.1.37
redox_termios-0.1.1
regex-0.2.6
regex-syntax-0.4.2
rhq-0.3.0
rhq-core-0.3.0
rustc-demangle-0.1.6
same-file-0.1.3
serde-1.0.27
serde_derive-1.0.27
serde_derive_internals-0.19.0
serde_json-1.0.9
shellexpand-1.0.0
strsim-0.7.0
syn-0.11.11
synom-0.11.3
termion-1.5.1
textwrap-0.9.0
thread_local-0.3.5
time-0.1.39
toml-0.4.5
unicode-bidi-0.3.4
unicode-normalization-0.1.5
unicode-width-0.1.4
unicode-xid-0.0.4
unreachable-1.0.0
url-1.7.0
utf8-ranges-1.0.0
vec_map-0.8.0
void-1.0.2
walkdir-1.0.7
winapi-0.2.8
winapi-0.3.4
winapi-build-0.1.1
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit bash-completion-r1 cargo

DESCRIPTION="A repository management tool"
HOMEPAGE="https://github.com/ubnt-intrepid/rhq"
SRC_URI="https://github.com/ubnt-intrepid/${PN}/archive/v${PV}.tar.gz -> ${P}.tar.gz
	$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="bash-completion fish-completion zsh-completion"

DEPEND=""
RDEPEND=""

src_install() {
	cargo_src_install

	dodoc CHANGELOG.md README.ja.md README.md

	outdir="${S}/target/$(usex debug "debug" "release")"

	if use bash-completion ; then
		"${outdir}/rhq" completion bash >rhq.bash
		newbashcomp rhq.bash rhq
	fi

	if use fish-completion ; then
		insinto /usr/share/fish/vendor_completions.d
		"${outdir}/rhq" completion fish >rhq.fish
		doins rhq.fish
	fi

	if use zsh-completion ; then
		insinto /usr/share/zsh/site-functions
		"${outdir}/rhq" completion zsh >_rhq
		doins _rhq
	fi
}
