# Copyright 2017-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.2.0

EAPI=7

CRATES="
aho-corasick-0.7.6
ansi_term-0.11.0
arrayref-0.3.5
arrayvec-0.5.1
atty-0.2.13
autocfg-0.1.7
backtrace-0.3.40
backtrace-sys-0.1.32
base64-0.10.1
bitflags-1.2.1
blake2b_simd-0.5.9
byteorder-1.3.2
cc-1.0.48
cfg-if-0.1.10
chrono-0.4.10
clap-2.33.0
cloudabi-0.0.3
constant_time_eq-0.1.4
crossbeam-utils-0.6.6
dirs-1.0.5
env_logger-0.5.13
failure-0.1.6
failure_derive-0.1.6
fuchsia-cprng-0.1.1
glob-0.2.11
humantime-1.3.0
idna-0.1.5
itoa-0.4.4
lazy_static-1.4.0
libc-0.2.66
log-0.4.8
matches-0.1.8
memchr-2.2.1
num-integer-0.1.41
num-traits-0.2.10
percent-encoding-1.0.1
proc-macro2-1.0.6
quick-error-1.2.2
quote-1.0.2
rand_core-0.3.1
rand_core-0.4.2
rand_os-0.1.3
rdrand-0.4.0
redox_syscall-0.1.56
redox_users-0.3.1
regex-1.3.1
regex-syntax-0.6.12
rust-argon2-0.5.1
rustc-demangle-0.1.16
ryu-1.0.2
same-file-1.0.5
serde-1.0.104
serde_derive-1.0.104
serde_json-1.0.44
shellexpand-1.1.0
smallvec-1.1.0
strsim-0.8.0
syn-1.0.11
synstructure-0.12.3
termcolor-1.0.5
textwrap-0.11.0
thread_local-0.3.6
time-0.1.42
toml-0.4.10
unicode-bidi-0.3.4
unicode-normalization-0.1.11
unicode-width-0.1.7
unicode-xid-0.2.0
url-1.7.2
vec_map-0.8.1
walkdir-2.2.9
winapi-0.3.8
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.2
winapi-x86_64-pc-windows-gnu-0.4.0
wincolor-1.0.2
"

inherit cargo git-r3

DESCRIPTION="A repository management tool"
HOMEPAGE="https://github.com/ubnt-intrepid/rhq"
SRC_URI="$(cargo_crate_uris ${CRATES})"
EGIT_REPO_URI="https://github.com/ubnt-intrepid/${PN}.git"
EGIT_COMMIT_DATE="$(ver_cut 5 ${PV})"
RESTRICT="mirror"
LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="bash-completion fish-completion zsh-completion"

DEPEND=""
RDEPEND=""

src_unpack() {
	git-r3_src_unpack
	cargo_src_unpack
}

src_install() {
	cargo_src_install

	dodoc docs/README.md docs/README.ja.md

	outdir="${S}/target/$(usex debug "debug" "release")"

	if use bash-completion ; then
		"${outdir}/rhq" completion bash >rhq.bash
		newbashcomp rhq.bash rhq
	fi

	if use fish-completion ; then
		insinto /usr/share/fish/vendor_completions.d
		"${outdir}/rhq" completion fish >rhq.fish
		doins rhq.fish
	fi

	if use zsh-completion ; then
		insinto /usr/share/zsh/site-functions
		"${outdir}/rhq" completion zsh >_rhq
		doins _rhq
	fi
}
