# Copyright 2017-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.1

EAPI=8

CRATES="
ansi_term-0.11.0
assert_cmd-0.12.0
atty-0.2.13
bitflags-1.2.1
cfg-if-0.1.10
clap-2.33.0
difference-2.0.0
doc-comment-0.3.3
dunce-1.0.1
escargot-0.5.0
getrandom-0.1.14
itoa-0.4.5
lazy_static-1.4.0
libc-0.2.66
log-0.4.8
ppv-lite86-0.2.6
predicates-1.0.4
predicates-core-1.0.0
predicates-tree-1.0.0
proc-macro2-1.0.9
quote-1.0.3
rand-0.7.3
rand_chacha-0.2.2
rand_core-0.5.1
rand_hc-0.2.0
redox_syscall-0.1.56
remove_dir_all-0.5.2
ryu-1.0.3
serde-1.0.104
serde_derive-1.0.104
serde_json-1.0.48
strsim-0.8.0
syn-1.0.16
tempfile-3.1.0
textwrap-0.11.0
treeline-0.1.0
unicode-width-0.1.7
unicode-xid-0.2.0
vec_map-0.8.1
wasi-0.9.0+wasi-snapshot-preview1
winapi-0.3.8
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="Linter for .env files"
HOMEPAGE="https://github.com/mgrachev/dotenv-linter"
SRC_URI="https://github.com/mgrachev/${PN}/archive/v${PV}.tar.gz -> ${P}.tar.gz
	$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="CC0-1.0 MIT || ( Apache-2.0 Boost-1.0 )"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

DEPEND=""
RDEPEND=""

src_install() {
	cargo_src_install

	dodoc CHANGELOG.md README.md
}
