# Copyright 2017-2019 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=6

CRATES="
aho-corasick-0.7.4
ansi_term-0.11.0
arrayvec-0.4.11
atty-0.2.13
backtrace-0.3.33
backtrace-sys-0.1.31
bitflags-1.1.0
cargo_metadata-0.8.1
cc-1.0.38
cfg-if-0.1.9
clap-2.33.0
crossbeam-deque-0.6.3
crossbeam-epoch-0.7.2
crossbeam-queue-0.1.2
crossbeam-utils-0.6.6
ctor-0.1.9
difference-2.0.0
either-1.5.2
failure-0.1.5
failure_derive-0.1.5
git2-0.9.2
home-0.3.4
humansize-1.1.0
idna-0.2.0
itoa-0.4.4
lazy_static-1.3.0
libc-0.2.60
libgit2-sys-0.8.2
libz-sys-1.0.25
log-0.4.7
matches-0.1.8
memchr-2.2.1
memoffset-0.5.1
nodrop-0.1.13
num_cpus-1.10.1
output_vt100-0.1.2
path-slash-0.1.1
percent-encoding-2.0.0
pkg-config-0.3.15
pretty_assertions-0.6.1
proc-macro2-0.4.30
quote-0.6.13
rayon-1.1.0
rayon-core-1.5.0
regex-1.2.0
regex-syntax-0.6.10
rustc-demangle-0.1.15
rustc_tools_util-0.2.0
rustc_version-0.2.3
ryu-1.0.0
same-file-1.0.5
scopeguard-0.3.3
scopeguard-1.0.0
semver-0.9.0
semver-parser-0.7.0
serde-1.0.97
serde_derive-1.0.97
serde_json-1.0.40
smallvec-0.6.10
strsim-0.8.0
syn-0.15.42
synstructure-0.10.2
textwrap-0.11.0
thread_local-0.3.6
ucd-util-0.1.5
unicode-bidi-0.3.4
unicode-normalization-0.1.8
unicode-width-0.1.5
unicode-xid-0.1.0
url-2.0.0
utf8-ranges-1.0.3
vcpkg-0.2.7
vec_map-0.8.1
walkdir-2.2.9
winapi-0.3.7
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.2
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="Manage cargo cache ($CARGO_HOME or ~/.cargo/), show sizes and remove directories selectively"
HOMEPAGE="https://github.com/matthiaskrgr/cargo-cache"
SRC_URI="https://github.com/matthiaskrgr/${PN}/archive/${PV}.tar.gz
	$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="|| ( MIT Apache-2.0 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=virtual/rust-1.31.0"
RDEPEND=""

src_install() {
	cargo_src_install --path .
}
