# Copyright 2017-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.1

EAPI=7

CRATES="
aho-corasick-0.7.15
ansi_term-0.11.0
atty-0.2.14
autocfg-1.0.1
bitflags-1.2.1
cargo-platform-0.1.1
cargo_metadata-0.12.3
cc-1.0.66
cfg-if-0.1.10
cfg-if-1.0.0
chrono-0.4.19
clap-2.33.3
const_fn-0.4.5
crossbeam-channel-0.5.0
crossbeam-deque-0.8.0
crossbeam-epoch-0.9.1
crossbeam-utils-0.8.1
ctor-0.1.18
difference-2.0.0
dirs-next-2.0.0
dirs-sys-next-0.1.2
either-1.6.1
form_urlencoded-1.0.0
fs_extra-1.2.0
getrandom-0.2.2
git2-0.13.15
hermit-abi-0.1.18
home-0.5.3
humansize-1.1.0
idna-0.2.0
itoa-0.4.7
jobserver-0.1.21
lazy_static-1.4.0
libc-0.2.82
libgit2-sys-0.12.17+1.1.0
libz-sys-1.1.2
log-0.4.13
matches-0.1.8
memchr-2.3.4
memoffset-0.6.1
num-integer-0.1.44
num-traits-0.2.14
num_cpus-1.13.0
output_vt100-0.1.2
path-slash-0.1.4
percent-encoding-2.1.0
pest-2.1.3
pkg-config-0.3.19
ppv-lite86-0.2.10
pretty_assertions-0.6.1
proc-macro2-1.0.24
quote-1.0.8
rand-0.8.2
rand_chacha-0.3.0
rand_core-0.6.1
rand_hc-0.3.0
rayon-1.5.0
rayon-core-1.9.0
redox_syscall-0.2.4
redox_users-0.4.0
regex-1.4.3
regex-syntax-0.6.22
remove_dir_all-0.5.3
remove_dir_all-0.6.1
rustc_tools_util-0.2.0
ryu-1.0.5
same-file-1.0.6
scopeguard-1.1.0
semver-0.11.0
semver-parser-0.10.2
serde-1.0.120
serde_derive-1.0.120
serde_json-1.0.61
strsim-0.8.0
syn-1.0.58
tempfile-3.2.0
textwrap-0.11.0
thread_local-1.1.0
time-0.1.44
tinyvec-1.1.0
tinyvec_macros-0.1.0
ucd-trie-0.1.3
unicode-bidi-0.3.4
unicode-normalization-0.1.16
unicode-width-0.1.8
unicode-xid-0.2.1
url-2.2.0
vcpkg-0.2.11
vec_map-0.8.2
walkdir-2.3.1
wasi-0.10.0+wasi-snapshot-preview1
winapi-0.3.9
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.5
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="Manage cargo cache, show sizes and remove directories selectively"
HOMEPAGE="https://github.com/matthiaskrgr/cargo-cache"
SRC_URI="https://github.com/matthiaskrgr/${PN}/archive/${PV}.tar.gz -> ${P}.tar.gz
	$(cargo_crate_uris ${CRATES})"
# Prevent portage from trying to fetch bunch of *.crate from mirror despite they are not mirrored.
RESTRICT="mirror"
LICENSE="MIT || ( Apache-2.0 Boost-1.0 )"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

DEPEND=""
RDEPEND=""

src_install() {
	cargo_src_install

	dodoc CHANGELOG.md README.md
}
