# Copyright 2017-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.1

EAPI=7

CRATES="
aho-corasick-0.7.13
ansi_term-0.11.0
arrayref-0.3.6
arrayvec-0.5.1
atty-0.2.14
autocfg-1.0.0
base64-0.11.0
bitflags-1.2.1
blake2b_simd-0.5.10
cargo_metadata-0.11.1
cc-1.0.58
cfg-if-0.1.10
chrono-0.4.13
clap-2.33.1
constant_time_eq-0.1.5
crossbeam-deque-0.7.3
crossbeam-epoch-0.8.2
crossbeam-queue-0.2.3
crossbeam-utils-0.7.2
ctor-0.1.15
difference-2.0.0
dirs-3.0.1
dirs-sys-0.3.5
either-1.5.3
fs_extra-1.1.0
getrandom-0.1.14
git2-0.13.8
hermit-abi-0.1.15
home-0.5.3
humansize-1.1.0
idna-0.2.0
itoa-0.4.6
jobserver-0.1.21
lazy_static-1.4.0
libc-0.2.74
libgit2-sys-0.12.9+1.0.1
libz-sys-1.0.25
log-0.4.11
matches-0.1.8
maybe-uninit-2.0.0
memchr-2.3.3
memoffset-0.5.5
num-integer-0.1.43
num-traits-0.2.12
num_cpus-1.13.0
output_vt100-0.1.2
path-slash-0.1.3
percent-encoding-2.1.0
pkg-config-0.3.18
ppv-lite86-0.2.8
pretty_assertions-0.6.1
proc-macro2-1.0.19
quote-1.0.7
rand-0.7.3
rand_chacha-0.2.2
rand_core-0.5.1
rand_hc-0.2.0
rayon-1.3.1
rayon-core-1.7.1
redox_syscall-0.1.57
redox_users-0.3.4
regex-1.3.9
regex-syntax-0.6.18
remove_dir_all-0.5.3
rust-argon2-0.7.0
rustc_tools_util-0.2.0
ryu-1.0.5
same-file-1.0.6
scopeguard-1.1.0
semver-0.10.0
semver-parser-0.7.0
serde-1.0.114
serde_derive-1.0.114
serde_json-1.0.57
strsim-0.8.0
syn-1.0.36
tempfile-3.1.0
textwrap-0.11.0
thread_local-1.0.1
time-0.1.43
tinyvec-0.3.3
unicode-bidi-0.3.4
unicode-normalization-0.1.13
unicode-width-0.1.8
unicode-xid-0.2.1
url-2.1.1
vcpkg-0.2.10
vec_map-0.8.2
walkdir-2.3.1
wasi-0.9.0+wasi-snapshot-preview1
winapi-0.3.9
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.5
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="Manage cargo cache, show sizes and remove directories selectively"
HOMEPAGE="https://github.com/matthiaskrgr/cargo-cache"
SRC_URI="https://github.com/matthiaskrgr/${PN}/archive/${PV}.tar.gz -> ${P}.tar.gz
	$(cargo_crate_uris ${CRATES})"
# Prevent portage from trying to fetch bunch of *.crate from mirror despite they are not mirrored.
RESTRICT="mirror"
LICENSE="BSD-2 CC0-1.0 MIT ZLIB || ( Apache-2.0 Boost-1.0 )"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

DEPEND=""
RDEPEND=""

src_install() {
	cargo_src_install

	dodoc CHANGELOG.md README.md
}
