# Copyright 2017-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.0

EAPI=7

CRATES="
aho-corasick-0.7.6
ansi_term-0.11.0
atty-0.2.13
autocfg-0.1.7
bitflags-1.2.1
c2-chacha-0.2.3
cargo_metadata-0.9.1
cc-1.0.48
cfg-if-0.1.10
clap-2.33.0
crossbeam-deque-0.7.2
crossbeam-epoch-0.8.0
crossbeam-queue-0.2.1
crossbeam-utils-0.7.0
ctor-0.1.12
difference-2.0.0
either-1.5.3
fs_extra-1.1.0
getrandom-0.1.13
git2-0.11.0
hermit-abi-0.1.5
home-0.5.1
humansize-1.1.0
idna-0.2.0
itoa-0.4.4
jobserver-0.1.17
lazy_static-1.4.0
libc-0.2.66
libgit2-sys-0.10.0
libz-sys-1.0.25
log-0.4.8
matches-0.1.8
memchr-2.2.1
memoffset-0.5.3
num_cpus-1.11.1
output_vt100-0.1.2
path-slash-0.1.1
percent-encoding-2.1.0
pkg-config-0.3.17
ppv-lite86-0.2.6
pretty_assertions-0.6.1
proc-macro2-1.0.7
quote-1.0.2
rand-0.7.2
rand_chacha-0.2.1
rand_core-0.5.1
rand_hc-0.2.0
rayon-1.3.0
rayon-core-1.7.0
redox_syscall-0.1.56
regex-1.3.1
regex-syntax-0.6.12
remove_dir_all-0.5.2
rustc_tools_util-0.2.0
rustc_version-0.2.3
ryu-1.0.2
same-file-1.0.5
scopeguard-1.0.0
semver-0.9.0
semver-parser-0.7.0
serde-1.0.104
serde_derive-1.0.104
serde_json-1.0.44
smallvec-1.1.0
strsim-0.8.0
syn-1.0.12
tempfile-3.1.0
textwrap-0.11.0
thread_local-0.3.6
unicode-bidi-0.3.4
unicode-normalization-0.1.11
unicode-width-0.1.7
unicode-xid-0.2.0
url-2.1.0
vcpkg-0.2.8
vec_map-0.8.1
walkdir-2.2.9
wasi-0.7.0
winapi-0.3.8
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.2
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="Manage cargo cache ($CARGO_HOME or ~/.cargo/), show sizes and remove directories selectively"
HOMEPAGE="https://github.com/matthiaskrgr/cargo-cache"
SRC_URI="https://github.com/matthiaskrgr/${PN}/archive/${PV}.tar.gz -> ${P}.tar.gz
	$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="|| ( MIT Apache-2.0 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""

src_install() {
	cargo_src_install

	dodoc CHANGELOG.md README.md
}
