# Copyright 2017-2019 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=6

CRATES="
aho-corasick-0.7.3
ansi_term-0.11.0
arrayvec-0.4.10
atty-0.2.11
autocfg-0.1.4
backtrace-0.3.24
backtrace-sys-0.1.28
bitflags-1.0.4
cargo_metadata-0.8.0
cc-1.0.37
cfg-if-0.1.9
clap-2.33.0
crossbeam-deque-0.2.0
crossbeam-epoch-0.3.1
crossbeam-utils-0.2.2
ctor-0.1.9
curl-sys-0.4.18
difference-2.0.0
either-1.5.2
failure-0.1.5
failure_derive-0.1.5
git2-0.8.0
home-0.3.4
humansize-1.1.0
idna-0.1.5
itoa-0.4.4
lazy_static-1.3.0
libc-0.2.55
libgit2-sys-0.7.11
libssh2-sys-0.2.11
libz-sys-1.0.25
log-0.4.6
matches-0.1.8
memchr-2.2.0
memoffset-0.2.1
nodrop-0.1.13
num_cpus-1.10.0
numtoa-0.1.0
openssl-probe-0.1.2
openssl-sys-0.9.47
output_vt100-0.1.2
path-slash-0.1.1
percent-encoding-1.0.1
pkg-config-0.3.14
pretty_assertions-0.6.1
proc-macro2-0.4.30
quote-0.6.12
rayon-1.0.3
rayon-core-1.4.1
redox_syscall-0.1.54
redox_termios-0.1.1
regex-1.1.6
regex-syntax-0.6.6
rustc-demangle-0.1.14
rustc_tools_util-0.2.0
ryu-0.2.8
same-file-1.0.4
scopeguard-0.3.3
semver-0.9.0
semver-parser-0.7.0
serde-1.0.91
serde_derive-1.0.91
serde_json-1.0.39
smallvec-0.6.9
strsim-0.8.0
syn-0.15.34
synstructure-0.10.2
termion-1.5.2
textwrap-0.11.0
thread_local-0.3.6
ucd-util-0.1.3
unicode-bidi-0.3.4
unicode-normalization-0.1.8
unicode-width-0.1.5
unicode-xid-0.1.0
url-1.7.2
utf8-ranges-1.0.2
vcpkg-0.2.6
vec_map-0.8.1
walkdir-2.2.7
winapi-0.3.7
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.2
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="Manage cargo cache ($CARGO_HOME or ~/.cargo/), show sizes and remove directories selectively"
HOMEPAGE="https://github.com/matthiaskrgr/cargo-cache"
SRC_URI="https://github.com/matthiaskrgr/${PN}/archive/${PV}.tar.gz
	$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="|| ( MIT Apache-2.0 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=virtual/rust-1.31.0"
RDEPEND=""

src_install() {
	cargo_src_install --path .
}
